In [41]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/heart-disease/heart_disease.csv

In [42]:
data=pd.read_csv("/kaggle/input/heart-disease/heart_disease.csv")
data.head(5)

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No

In [43]:
data.shape

(10000, 21)

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   object
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   object
 5   Smoking               9975 non-null   object
 6   Family Heart Disease  9979 non-null   object
 7   Diabetes              9970 non-null   object
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   object
 10  Low HDL Cholesterol   9975 non-null   object
 11  High LDL Cholesterol  9974 non-null   object
 12  Alcohol Consumption   7414 non-null   object
 13  Stress Level          9978 non-null   object
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   object
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  object
dtypes: float64(9), object(12)
memory usage: 1.6+ MB

In [45]:
data.drop(columns=['Exercise Habits','Family Heart Disease','Sugar Consumption','Alcohol Consumption','Triglyceride Level','Fasting Blood Sugar','CRP Level'],inplace=True)

In [46]:
data.isnull().sum()

Age                     29
Gender                  19
Blood Pressure          19
Cholesterol Level       30
Smoking                 25
Diabetes                30
BMI                     22
High Blood Pressure     26
Low HDL Cholesterol     25
High LDL Cholesterol    26
Stress Level            22
Sleep Hours             25
Homocysteine Level      20
Heart Disease Status     0
dtype: int64

In [47]:
data['Age']=data['Age'].fillna(data['Age'].mean())
data['Blood Pressure']=data['Blood Pressure'].fillna(data['Blood Pressure'].mean())
data['Cholesterol Level']=data['Cholesterol Level'].fillna(data['Cholesterol Level'].mean())
data['BMI']=data['BMI'].fillna(data['BMI'].mean())
data['Sleep Hours']=data['Sleep Hours'].fillna(data['Sleep Hours'].mean())
data['Homocysteine Level']=data['Homocysteine Level'].fillna(data['Homocysteine Level'].mean())

In [48]:
data['Gender']=data['Gender'].fillna(data['Gender'].mode()[0])
data['Smoking']=data['Smoking'].fillna(data['Smoking'].mode()[0])
data['Diabetes']=data['Diabetes'].fillna(data['Diabetes'].mode()[0])
data['High Blood Pressure']=data['High Blood Pressure'].fillna(data['High Blood Pressure'].mode()[0])
data['Low HDL Cholesterol']=data['Low HDL Cholesterol'].fillna(data['Low HDL Cholesterol'].mode()[0])
data['High LDL Cholesterol']=data['High LDL Cholesterol'].fillna(data['High LDL Cholesterol'].mode()[0])
data['Stress Level']=data['Stress Level'].fillna(data['Stress Level'].mode()[0])

In [49]:
data.head(7)

,Age,Gender,Blood Pressure,Cholesterol Level,Smoking,Diabetes,BMI,High Blood Pressure,Low HDL Cholesterol,High LDL Cholesterol,Stress Level,Sleep Hours,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,Yes,No,24.991591,Yes,Yes,No,Medium,7.633228,12.387250,No
1,69.0,Female,146.0,286.0,No,Yes,25.221799,No,Yes,No,High,8.744034,19.298875,No
2,46.0,Male,126.0,216.0,No,No,29.855447,No,Yes,Yes,Low,4.440440,11.230926,No
3,32.0,Female,122.0,293.0,Yes,No,24.130477,Yes,No,Yes,High,5.249405,5.961958,No
4,60.0,Male,166.0,242.0,Yes,Yes,20.486289,Yes,No,No,High,7.030971,8.153887,No
5,25.0,Male,152.0,257.0,Yes,No,28.144681,No,No,No,Medium,5.504876,10.815983,No
6,78.0,Female,121.0,175.0,Yes,Yes,18.042332,No,Yes,No,Medium,9.240911,19.659461,No

In [50]:
from sklearn.preprocessing import OneHotEncoder

In [51]:
# one=data[['Gender','Smoking','Diabetes','High Blood Pressure','Low HDL Cholesterol','High LDL Cholesterol','Alcohol Consumption','Stress Level']]

In [52]:
ohe=OneHotEncoder()
data['Gender']=ohe.fit_transform(data[['Gender']]).toarray()
data['Smoking']=ohe.fit_transform(data[['Smoking']]).toarray()
data['Diabetes']=ohe.fit_transform(data[['Diabetes']]).toarray()
data['High Blood Pressure']=ohe.fit_transform(data[['High Blood Pressure']]).toarray()
data['Low HDL Cholesterol']=ohe.fit_transform(data[['Low HDL Cholesterol']]).toarray()
data['High LDL Cholesterol']=ohe.fit_transform(data[['High LDL Cholesterol']]).toarray()
data['Stress Level']=ohe.fit_transform(data[['Stress Level']]).toarray()

In [53]:
data.head(3)

,Age,Gender,Blood Pressure,Cholesterol Level,Smoking,Diabetes,BMI,High Blood Pressure,Low HDL Cholesterol,High LDL Cholesterol,Stress Level,Sleep Hours,Homocysteine Level,Heart Disease Status
0,56.0,0.0,153.0,155.0,0.0,1.0,24.991591,0.0,0.0,1.0,0.0,7.633228,12.387250,No
1,69.0,1.0,146.0,286.0,1.0,0.0,25.221799,1.0,0.0,1.0,1.0,8.744034,19.298875,No
2,46.0,0.0,126.0,216.0,1.0,1.0,29.855447,1.0,0.0,0.0,0.0,4.440440,11.230926,No

In [54]:
x=data.iloc[:,:-1]
y=data['Heart Disease Status']

In [55]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [64]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)*100

80.65

In [65]:
data.head(2)

,Age,Gender,Blood Pressure,Cholesterol Level,Smoking,Diabetes,BMI,High Blood Pressure,Low HDL Cholesterol,High LDL Cholesterol,Stress Level,Sleep Hours,Homocysteine Level,Heart Disease Status
0,56.0,0.0,153.0,155.0,0.0,1.0,24.991591,0.0,0.0,1.0,0.0,7.633228,12.387250,No
1,69.0,1.0,146.0,286.0,1.0,0.0,25.221799,1.0,0.0,1.0,1.0,8.744034,19.298875,No

In [66]:
rf.predict([[56.0,0.0,153.0,155.0,0.0,1.0,24.991591,0.0,0.0,1.0,0.0,7.633228,12.387250]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array(['No'], dtype=object)